# Generated by Django 5.1.1 on 2024-10-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeProductos', '0003_alter_producto_caracteristica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caracteristica',
        ),
    ]
