# Generated by Django 5.1.1 on 2024-11-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeProductos', '0005_producto_caracteristica_alter_producto_precio'),
    ]

    operations = [
    ]
