# Generated by Django 5.1.1 on 2024-11-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDeProductos', '0006_auto_20241118_1857'),
        ('GestionDeProductos', '0007_auto_20241118_1859'),
    ]

    operations = [
    ]
